### ISSUE TITLE
'Invalid string format' error on Sign and Submit

### ISSUE THREAD

**Issue by dckc** [0xpatrickdev/agoric-gov-proposal-hub#46]
What we did:
1. start local chain; choose local chain; connect wallet with user1
2. on param change tab, change storage fee from 0.002 to 0.00002
3. sign and submit

then we got a toast with `Invalid string format`.

stack from testing with @dtribble... I think @kriskowal hit this too?

<details><summary>console stack traces</summary>
```
(Error#1)
error @ index-b4ba3a26.js:40
index-b4ba3a26.js:38 Error#1: Invalid string format
nn @ index-b4ba3a26.js:38
index-b4ba3a26.js:40   at Int53.fromString (https://cosgov.org/assets/index-b4ba3a26.js:66:116305)
  at dn.signDirect (https://cosgov.org/assets/index-b4ba3a26.js:69:116259)
  at async dn.signAndBroadcast (https://cosgov.org/assets/index-b4ba3a26.js:69:113981)
  at async It (https://cosgov.org/assets/index-b4ba3a26.js:106:84913)
  at async https://cosgov.org/assets/index-b4ba3a26.js:106:86328

nn @ index-b4ba3a26.js:40
4index-b4ba3a26.js:40 "stargate", "no-legacy-stdTx" feature has been deprecated. The launchpad is no longer supported, thus works without the two features. We would keep the aforementioned two feature for a while, but the upcoming update would potentially cause errors. Remove the two feature.
warn @ index-b4ba3a26.js:40
(anonymous) @ injectedScript.bundle.js:2
(anonymous) @ injectedScript.bundle.js:2
r @ injectedScript.bundle.js:2
experimentalSuggestChain @ injectedScript.bundle.js:2
suggestChain @ index-b4ba3a26.js:88
await in suggestChain (async)
(anonymous) @ index-b4ba3a26.js:106
WalletContextProvider @ index-b4ba3a26.js:106
Xh @ index-b4ba3a26.js:64
dj @ index-b4ba3a26.js:66
Wk @ index-b4ba3a26.js:66
Vk @ index-b4ba3a26.js:66
Uk @ index-b4ba3a26.js:66
Jk @ index-b4ba3a26.js:66
Hk @ index-b4ba3a26.js:66
dn @ index-b4ba3a26.js:51
un @ index-b4ba3a26.js:51
index-b4ba3a26.js:40 SES_UNHANDLED_REJECTION: (Error#2)
error @ index-b4ba3a26.js:40
(anonymous) @ index-b4ba3a26.js:40
Ct @ index-b4ba3a26.js:40
index-b4ba3a26.js:38 Error#2: Request rejected
nn @ index-b4ba3a26.js:38
Ot @ index-b4ba3a26.js:38
error @ index-b4ba3a26.js:40
(anonymous) @ index-b4ba3a26.js:40
Ct @ index-b4ba3a26.js:40
index-b4ba3a26.js:40   at n (chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/injectedScript.bundle.js:2:51896)

nn @ index-b4ba3a26.js:40
Ot @ index-b4ba3a26.js:38
error @ index-b4ba3a26.js:40
(anonymous) @ index-b4ba3a26.js:40
Ct @ index-b4ba3a26.js:40
index-b4ba3a26.js:40 SES_UNHANDLED_REJECTION: (Error#3)
error @ index-b4ba3a26.js:40
(anonymous) @ index-b4ba3a26.js:40
Ct @ index-b4ba3a26.js:40
index-b4ba3a26.js:38 Error#3: Request rejected
nn @ index-b4ba3a26.js:38
Ot @ index-b4ba3a26.js:38
error @ index-b4ba3a26.js:40
(anonymous) @ index-b4ba3a26.js:40
Ct @ index-b4ba3a26.js:40
index-b4ba3a26.js:40   at n (chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/injectedScript.bundle.js:2:51896)

nn @ index-b4ba3a26.js:40
Ot @ index-b4ba3a26.js:38
error @ index-b4ba3a26.js:40
(anonymous) @ index-b4ba3a26.js:40
Ct @ index-b4ba3a26.js:40
index-b4ba3a26.js:40 (Error#4)
error @ index-b4ba3a26.js:40
It @ index-b4ba3a26.js:106
await in It (async)
vt @ index-b4ba3a26.js:106
await in vt (async)
Zt @ index-b4ba3a26.js:106
Nb @ index-b4ba3a26.js:63
Tb @ index-b4ba3a26.js:63
Ub @ index-b4ba3a26.js:63
nf @ index-b4ba3a26.js:63
se$1 @ index-b4ba3a26.js:63
(anonymous) @ index-b4ba3a26.js:63
Rk @ index-b4ba3a26.js:66
Jb @ index-b4ba3a26.js:63
hd @ index-b4ba3a26.js:63
fd @ index-b4ba3a26.js:63
ed @ index-b4ba3a26.js:63
index-b4ba3a26.js:38 Error#4: Invalid string format
nn @ index-b4ba3a26.js:38
Ot @ index-b4ba3a26.js:38
error @ index-b4ba3a26.js:40
It @ index-b4ba3a26.js:106
await in It (async)
vt @ index-b4ba3a26.js:106
await in vt (async)
Zt @ index-b4ba3a26.js:106
Nb @ index-b4ba3a26.js:63
Tb @ index-b4ba3a26.js:63
Ub @ index-b4ba3a26.js:63
nf @ index-b4ba3a26.js:63
se$1 @ index-b4ba3a26.js:63
(anonymous) @ index-b4ba3a26.js:63
Rk @ index-b4ba3a26.js:66
Jb @ index-b4ba3a26.js:63
hd @ index-b4ba3a26.js:63
fd @ index-b4ba3a26.js:63
ed @ index-b4ba3a26.js:63
index-b4ba3a26.js:40   at Int53.fromString (https://cosgov.org/assets/index-b4ba3a26.js:66:116305)
  at dn.signDirect (https://cosgov.org/assets/index-b4ba3a26.js:69:116259)
  at async dn.signAndBroadcast (https://cosgov.org/assets/index-b4ba3a26.js:69:113981)
  at async It (https://cosgov.org/assets/index-b4ba3a26.js:106:84913)
  at async vt (https://cosgov.org/assets/index-b4ba3a26.js:106:85780)
```
</details>

**Comment by dckc** [comment]
@0xpatrickdev notes a work-around:

Example of command line usage for the interim: https://github.com/0xpatrickdev/agoric-vault-collateral-proposal#proposal-steps (edited)

**Comment by 0xpatrickdev** [comment]
Thank you @dckc. Fixed here: https://github.com/DCFoundation/cosmos-proposal-builder/pull/5
